version: '3.8'

services:
  maritime-qbank:
    build: .
    container_name: maritime_qbank_app
    ports:
      - "3001:3001"
    volumes:
      - sqlite_data:/app/server
    restart: always

volumes:
  sqlite_data: